"""add twitter_username to user

Revision ID: 0d74ad151cbe
Revises: 6a667f089d57
Create Date: 2019-04-03 08:15:55.346141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d74ad151cbe'
down_revision = '6a667f089d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_username', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_username')
    # ### end Alembic commands ###
