"""add site_admin flag on user

Revision ID: 101e809396bd
Revises: f250c66f464e
Create Date: 2018-11-27 19:01:11.083050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101e809396bd'
down_revision = 'f250c66f464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('site_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'site_admin')
    # ### end Alembic commands ###
