"""move conference settings to DB

Revision ID: 126d519970b8
Revises: 219a9aa714da
Create Date: 2018-11-21 10:01:07.906369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126d519970b8'
down_revision = '219a9aa714da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference',
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('informal_name', sa.String(length=256), nullable=False),
    sa.Column('talk_lengths', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('conference_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conference')
    # ### end Alembic commands ###
