"""proposal and voting windows

Revision ID: 224984e82a90
Revises: d59092b1b138
Create Date: 2019-05-05 12:57:47.420095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224984e82a90'
down_revision = 'd59092b1b138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('proposals_begin', sa.DateTime(), nullable=True))
    op.add_column('conference', sa.Column('proposals_end', sa.DateTime(), nullable=True))
    op.add_column('conference', sa.Column('voting_begin', sa.DateTime(), nullable=True))
    op.add_column('conference', sa.Column('voting_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'voting_end')
    op.drop_column('conference', 'voting_begin')
    op.drop_column('conference', 'proposals_end')
    op.drop_column('conference', 'proposals_begin')
    # ### end Alembic commands ###
