"""add reviewer field to user

Revision ID: 291c360aca4b
Revises: 7a6fff9daf7f
Create Date: 2019-09-11 00:22:21.591222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291c360aca4b'
down_revision = '7a6fff9daf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reviewer', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reviewer')
    # ### end Alembic commands ###
