"""add conference website field

Revision ID: 2fc197a68be9
Revises: 224984e82a90
Create Date: 2019-05-11 16:15:50.369004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc197a68be9'
down_revision = '224984e82a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('website', sa.String(length=512), nullable=True))

    op.execute("UPDATE conference SET website = 'https://2019.pygotham.org/' WHERE informal_name = 'PyGotham'")

    # The field *should* be not-null, but we can't guess the right values for any
    # other conferences using Yak-Bak at this time; so put in a placeholder for them
    op.execute("UPDATE conference SET website = 'http://www.example.com/' WHERE informal_name != 'PyGotham'")

    op.alter_column('conference', 'website', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'website')
    # ### end Alembic commands ###
