"""add UsedMagicLink model

Revision ID: 429ba11d0fd7
Revises: d996c0670fc6
Create Date: 2019-03-25 22:32:43.065167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429ba11d0fd7'
down_revision = 'd996c0670fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_magic_link',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('used_on', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_magic_link')
    # ### end Alembic commands ###
