"""add audience takeaways field to Talk

Revision ID: 474a5e05c155
Revises: db5ac35dacaa
Create Date: 2019-03-03 19:46:14.795762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474a5e05c155'
down_revision = 'db5ac35dacaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talk', sa.Column('take_aways', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'take_aways')
    # ### end Alembic commands ###
