"""add talk table

Revision ID: 4b6f3303e7da
Revises: e51e178df6ae
Create Date: 2018-06-03 15:42:07.536453

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6f3303e7da'
down_revision = 'e51e178df6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talk',
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('overview', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outline', sa.Text(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('talk_id')
    )
    op.create_table('talk_speaker',
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['talk_id'], ['talk.talk_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('talk_id', 'user_id')
    )

    op.add_column('user', sa.Column('created', sa.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.TIMESTAMP(), nullable=True))

    op.execute("set time zone utc")
    op.execute("update public.user set created = now(), updated = now()")

    op.alter_column('user', 'created', nullable=False)
    op.alter_column('user', 'updated', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    op.drop_table('talk_speaker')
    op.drop_table('talk')
    # ### end Alembic commands ###
