"""add category

Revision ID: 6789491dbe84
Revises: 6c261e5e5478
Create Date: 2019-04-12 08:57:41.712581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6789491dbe84'
down_revision = '6c261e5e5478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('talk_category',
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['talk_id'], ['talk.talk_id'], ),
    sa.PrimaryKeyConstraint('talk_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talk_category')
    op.drop_table('category')
    # ### end Alembic commands ###
