"""add speaker_bio to user

Revision ID: 6a667f089d57
Revises: f15cfbfdd3d7
Create Date: 2019-03-31 14:30:52.495255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a667f089d57'
down_revision = 'f15cfbfdd3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('speaker_bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'speaker_bio')
    # ### end Alembic commands ###
