"""edit cfp phases

Revision ID: 6a8bde29960e
Revises: d59092b1b138
Create Date: 2019-05-05 08:53:03.092251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8bde29960e'
down_revision = 'd59092b1b138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('allow_new_talks', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('conference', sa.Column('allow_talk_edits', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('conference', sa.Column('allow_voting', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'allow_voting')
    op.drop_column('conference', 'allow_talk_edits')
    op.drop_column('conference', 'allow_new_talks')
    # ### end Alembic commands ###
