"""add talk status

Revision ID: 6c261e5e5478
Revises: 0d74ad151cbe
Create Date: 2019-04-03 22:28:11.915764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c261e5e5478'
down_revision = '0d74ad151cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum_type = sa.Enum('PROPOSED', 'WITHDRAWN', name='talkstatus')
    enum_type.create(op.get_bind(), checkfirst=False)

    op.add_column('talk', sa.Column('state', enum_type, server_default='PROPOSED', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'state')
    op.execute('DROP TYPE talkstatus')
    # ### end Alembic commands ###
