"""add vote comment

Revision ID: 7a6fff9daf7f
Revises: aa460d47bb07
Create Date: 2019-09-10 22:40:52.929576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6fff9daf7f'
down_revision = 'aa460d47bb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'comment')
    # ### end Alembic commands ###
