"""Add conference footer text

Revision ID: 83f854ad34c4
Revises: ebadb425d3af
Create Date: 2019-05-18 06:36:42.142489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f854ad34c4'
down_revision = 'ebadb425d3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('footer_text', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'footer_text')
    # ### end Alembic commands ###
