"""add conference review window

Revision ID: 9534beed69d6
Revises: 824e2d900c44
Create Date: 2019-05-27 07:26:21.009072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9534beed69d6'
down_revision = '824e2d900c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('review_begin', sa.DateTime(), nullable=True))
    op.add_column('conference', sa.Column('review_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'review_end')
    op.drop_column('conference', 'review_begin')
    # ### end Alembic commands ###
