"""add voting table

Revision ID: d37acb063af6
Revises: 224984e82a90
Create Date: 2019-05-12 21:02:22.724372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd37acb063af6'
down_revision = 'c4ded044814d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.CheckConstraint('value is NULL OR value IN (-1, 0, 1)', name='ck_vote_values'),
    sa.ForeignKeyConstraint(['talk_id'], ['talk.talk_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('talk_id', 'user_id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
