"""talk anonymization

Revision ID: d59092b1b138
Revises: 6789491dbe84
Create Date: 2019-05-02 16:15:05.472729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59092b1b138'
down_revision = '6789491dbe84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talk', sa.Column('anonymized_description', sa.Text(), nullable=True))
    op.add_column('talk', sa.Column('anonymized_outline', sa.Text(), nullable=True))
    op.add_column('talk', sa.Column('anonymized_title', sa.String(length=512), nullable=True))
    op.add_column('talk', sa.Column('has_anonymization_changes', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('talk', sa.Column('is_anonymized', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'is_anonymized')
    op.drop_column('talk', 'has_anonymization_changes')
    op.drop_column('talk', 'anonymized_title')
    op.drop_column('talk', 'anonymized_outline')
    op.drop_column('talk', 'anonymized_description')
    # ### end Alembic commands ###
