"""add cfp_email to conference

Revision ID: d996c0670fc6
Revises: 1c38826de235
Create Date: 2019-03-25 20:33:16.216616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd996c0670fc6'
down_revision = '1c38826de235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conference', sa.Column('cfp_email', sa.String(length=256), nullable=True))
    op.execute("UPDATE conference SET cfp_email = 'program@pygotham.org'")
    op.alter_column('conference', 'cfp_email', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'cfp_email')
    # ### end Alembic commands ###
