"""add TalkSpeaker association table

Revision ID: db5ac35dacaa
Revises: 101e809396bd
Create Date: 2019-03-02 16:30:34.362603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5ac35dacaa'
down_revision = '101e809396bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum_type = sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'DELETED', name='invitationstatus')
    enum_type.create(op.get_bind(), checkfirst=False)

    op.add_column('talk_speaker', sa.Column('state', enum_type, nullable=True))
    op.execute("UPDATE talk_speaker SET state = 'CONFIRMED'")
    op.alter_column('talk_speaker', 'state', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk_speaker', 'state')
    # ### end Alembic commands ###
