"""Add ConductReport table

Revision ID: ebadb425d3af
Revises: d37acb063af6
Create Date: 2019-05-15 04:54:40.196372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebadb425d3af'
down_revision = 'd37acb063af6'
branch_labels = None
depends_on = None

ConductReportStatus = sa.Enum('REPORTED', 'AWAITING_RESPONSE', 'RESOLVED', name='conductreportstatus')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conduct_report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', ConductReportStatus, nullable=True),
    sa.ForeignKeyConstraint(['talk_id'], ['talk.talk_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conference', sa.Column('conduct_email', sa.String(length=256), nullable=True))
    op.execute("UPDATE conference SET conduct_email='organizers@pycon.ca'")
    op.alter_column('conference', 'conduct_email', existing_type=sa.VARCHAR(length=256), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conference', 'conduct_email')
    op.drop_table('conduct_report')
    ConductReportStatus.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
