"""add created/updated to models

Revision ID: f15cfbfdd3d7
Revises: 429ba11d0fd7
Create Date: 2019-03-27 10:09:08.529341

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15cfbfdd3d7'
down_revision = '429ba11d0fd7'
branch_labels = None
depends_on = None


def add_date_column(table, column):
    if column.nullable:
        op.add_column(table, column)
        return

    col = sa.Column(column.name, sa.TIMESTAMP(),nullable=True)
    op.add_column(table, col)
    conn = op.get_bind()
    conn.execute(sa.text(f"UPDATE {table} SET {column.name} = :now"), now=datetime.utcnow())
    op.alter_column(table, column.name, nullable=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_date_column('conference', sa.Column('created', sa.TIMESTAMP(), nullable=False))
    add_date_column('conference', sa.Column('updated', sa.TIMESTAMP(), nullable=False))
    add_date_column('demographic_survey', sa.Column('created', sa.TIMESTAMP(), nullable=False))
    add_date_column('demographic_survey', sa.Column('updated', sa.TIMESTAMP(), nullable=False))
    add_date_column('talk_speaker', sa.Column('created', sa.TIMESTAMP(), nullable=False))
    add_date_column('talk_speaker', sa.Column('updated', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk_speaker', 'updated')
    op.drop_column('talk_speaker', 'created')
    op.drop_column('demographic_survey', 'updated')
    op.drop_column('demographic_survey', 'created')
    op.drop_column('conference', 'updated')
    op.drop_column('conference', 'created')
    # ### end Alembic commands ###
